#!/usr/bin/env python3
"""Convert a recorded menu-event stream (menu.ndjson) into a Godot RAPTOR_PLAYTHROUGH
script, so a *live* C menu recording can be replayed in Godot and diffed the same way
the hand-written menu-parity scenarios are.

Pipeline:
    C record  ->  menu.ndjson  --(this tool)-->  replay.txt
    replay.txt --(RAPTOR_PLAYTHROUGH in Godot, RAPTOR_MENU_OUT)--> godot.menu.ndjson
    parity_diff.py --menu --c-golden menu.ndjson --godot-out godot.menu.ndjson

Each menu.ndjson row is one menu input event carrying the raw C scancode (GFX/KEYS.H
SC_*). We map each scancode to the Playthrough.cs `key NAME` token and emit one key
per event, separated by the load-bearing 30-frame gap (shorter gaps race C's
SWD_Dialog busy-spin and register nondeterministically — see menu_main_nav.txt).

Limits (reported, never silently swallowed):
  * Only `kind == "key"` rows replay. Mouse rows (kind == "click") can't be expressed
    by the .txt `key` vocabulary, so they are skipped WITH A WARNING and the run is
    flagged unreplayable (a keyboard-only recording converts cleanly).
  * Scancodes with no mapping are skipped WITH A WARNING and flag the run; extend
    SCANCODE_TO_KEY below as new keys show up in real recordings.
"""

from __future__ import annotations

import argparse
import json
import sys

# GFX/KEYS.H SC_* (the scancode echoed in menu.ndjson) -> Playthrough.cs `key` token.
# The token must match InteractiveInputController.KeyEventToMenuAction / the existing
# dosraptor/tests/scripts/*.txt vocabulary.
SCANCODE_TO_KEY: dict[int, str] = {
    0x01: "Escape",
    0x0E: "Backspace",
    0x0F: "Tab",
    0x1C: "Return",   # SC_ENTER
    0x39: "Space",
    0x47: "Home",
    0x48: "Up",
    0x49: "PageUp",
    0x4B: "Left",
    0x4D: "Right",
    0x4F: "End",
    0x50: "Down",
    0x51: "PageDown",
    0x53: "Delete",
    # Function keys F1..F12.
    0x3B: "F1", 0x3C: "F2", 0x3D: "F3", 0x3E: "F4", 0x3F: "F5", 0x40: "F6",
    0x41: "F7", 0x42: "F8", 0x43: "F9", 0x44: "F10", 0x57: "F11", 0x58: "F12",
    # Digit row 1..9,0.
    0x02: "1", 0x03: "2", 0x04: "3", 0x05: "4", 0x06: "5",
    0x07: "6", 0x08: "7", 0x09: "8", 0x0A: "9", 0x0B: "0",
    # Letters (DOS scancode order) -> uppercase token, as the name-entry scripts use.
    0x10: "Q", 0x11: "W", 0x12: "E", 0x13: "R", 0x14: "T", 0x15: "Y",
    0x16: "U", 0x17: "I", 0x18: "O", 0x19: "P",
    0x1E: "A", 0x1F: "S", 0x20: "D", 0x21: "F", 0x22: "G", 0x23: "H",
    0x24: "J", 0x25: "K", 0x26: "L",
    0x2C: "Z", 0x2D: "X", 0x2E: "C", 0x2F: "V", 0x30: "B", 0x31: "N", 0x32: "M",
}

# C records keys at human pace; the menu harness requires >= 30-frame gaps so the
# replayed key can't race the SWD busy-spin. See menu_main_nav.txt header.
GAP_FRAMES = 30
TAIL_FRAMES = 40


def read_menu_events(path: str) -> list[dict]:
    rows = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def to_playthrough(rows: list[dict], source: str) -> tuple[list[str], list[str]]:
    """Return (script_lines, warnings). Warnings are non-fatal but flag a run that
    won't replay byte-identically (so the caller can refuse to trust the diff)."""
    out = [
        f"# Auto-generated by ndjson_to_menu_playthrough.py from {source}",
        f"# {len(rows)} recorded menu events; {GAP_FRAMES}-frame gaps (determinism).",
        "",
        f"wait {GAP_FRAMES}",
    ]
    warnings: list[str] = []
    emitted = 0
    for row in rows:
        idx = row.get("event_index", "?")
        kind = row.get("kind", "key")
        if kind != "key":
            warnings.append(
                f"event {idx}: kind={kind!r} (mouse) cannot be replayed by a key script — skipped"
            )
            continue
        sc = row.get("scancode")
        key = SCANCODE_TO_KEY.get(sc) if isinstance(sc, int) else None
        if key is None:
            shown = f"{sc} (0x{sc:02x})" if isinstance(sc, int) else repr(sc)
            warnings.append(f"event {idx}: unmapped scancode {shown} — skipped")
            continue
        out.append(f"key {key}")
        out.append(f"wait {GAP_FRAMES}")
        emitted += 1
    out.append(f"wait {TAIL_FRAMES}")
    out.append("quit")
    if emitted == 0:
        warnings.append("no replayable key events — the resulting script is empty")
    return out, warnings


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", required=True, help="recorded menu.ndjson")
    ap.add_argument("--output", required=True, help="Godot RAPTOR_PLAYTHROUGH .txt to write")
    args = ap.parse_args(argv)

    rows = read_menu_events(args.input)
    script, warnings = to_playthrough(rows, args.input)
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write("\n".join(script) + "\n")

    for w in warnings:
        print(f"ndjson_to_menu_playthrough: WARN {w}", file=sys.stderr)
    print(
        f"ndjson_to_menu_playthrough: {len(rows)} events -> {args.output} "
        f"({len(warnings)} warnings)",
        file=sys.stderr,
    )
    # Unmapped/mouse events mean the replay won't match the golden 1:1 — exit nonzero
    # so a wrapping pipeline can refuse rather than diff a known-incomplete script.
    return 1 if warnings else 0


if __name__ == "__main__":
    raise SystemExit(main())
